
application.properties
spring.application.name=Springwebdb

spring.config.import=optional:classpath:application-secret.properties

spring.datasource.url=jdbc:mysql://localhost:3306/springbootperson
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.configuration.map-underscore-to-camel-case=true